name: car_pooling
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  day_night_time_picker: ^1.3.1
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  get: ^4.7.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: any
  intl_phone_field: ^3.2.0
  vector_graphics: ^1.1.18
  loading_animation_widget: ^1.3.0
  pinput: ^5.0.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  flutter_localizations:
    sdk: flutter
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/common/
    - assets/icons/
